// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: gramatica/LexerFormulario.flex

import java_cup.runtime.*;
import java.util.ArrayList;
import com.example.pokemonformularios.reportes.ErrorCompi;


@SuppressWarnings("fallthrough")
public class LexerFormulario implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\22\0\1\1"+
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\0\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\12\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\0\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\56\1\57\1\60\1\61\1\62"+
    "\1\63\1\64\1\0\1\65\1\66\1\67\1\0\1\70"+
    "\1\71\1\72\1\73\1\74\1\75\1\76\1\77\1\100"+
    "\1\43\1\101\1\102\1\103\1\104\1\105\1\106\1\43"+
    "\1\107\1\110\1\111\1\112\1\43\1\113\1\43\1\114"+
    "\1\43\1\115\1\116\1\117\1\120\6\0\1\3\u01a2\0"+
    "\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\2\1\5"+
    "\1\1\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\23\25\1\26\1\27\1\30\13\25\1\31\1\1\1\32"+
    "\1\3\1\33\1\34\1\0\1\2\1\35\2\0\1\36"+
    "\4\0\1\37\1\40\1\41\2\25\1\42\5\25\1\43"+
    "\22\25\1\44\11\25\1\45\5\0\1\46\2\0\7\25"+
    "\1\47\7\25\1\50\3\25\1\51\24\25\4\0\1\25"+
    "\1\52\4\25\1\53\2\25\1\54\1\55\7\25\1\56"+
    "\6\25\1\57\14\25\5\0\1\60\4\25\1\61\7\25"+
    "\1\62\1\25\1\63\1\64\5\25\1\65\10\25\1\66"+
    "\3\0\1\25\1\67\1\70\4\25\1\71\4\25\1\72"+
    "\3\25\1\73\1\74\2\25\1\75\1\76\1\25\1\77"+
    "\1\100\1\25\1\101\1\0\1\102\1\0\1\103\1\104"+
    "\5\25\1\105\2\25\1\106\1\107\1\25\1\110\1\25"+
    "\1\111\7\25\1\112\1\113\13\25\1\114\2\25\1\115"+
    "\7\25\1\116\6\25\1\117\1\25\1\120\6\25\1\121"+
    "\3\25\1\122\2\25\1\123";

  private static int [] zzUnpackAction() {
    int [] result = new int[345];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\121\0\242\0\363\0\u0144\0\u0195\0\u01e6\0\121"+
    "\0\u0237\0\u0288\0\121\0\121\0\121\0\121\0\121\0\u02d9"+
    "\0\u032a\0\u037b\0\121\0\121\0\u03cc\0\u041d\0\u046e\0\121"+
    "\0\u04bf\0\u0510\0\u0561\0\u05b2\0\u0603\0\u0654\0\u06a5\0\u06f6"+
    "\0\u0747\0\u0798\0\u07e9\0\u083a\0\u088b\0\u08dc\0\u092d\0\u097e"+
    "\0\u09cf\0\u0a20\0\u0a71\0\121\0\121\0\121\0\u0ac2\0\u0b13"+
    "\0\u0b64\0\u0bb5\0\u0c06\0\u0c57\0\u0ca8\0\u0cf9\0\u0d4a\0\u0d9b"+
    "\0\u0dec\0\121\0\u0e3d\0\121\0\121\0\121\0\121\0\u0e8e"+
    "\0\121\0\121\0\u0288\0\u0edf\0\121\0\u0f30\0\u0f81\0\u0fd2"+
    "\0\u1023\0\121\0\121\0\121\0\u1074\0\u10c5\0\u1116\0\u1167"+
    "\0\u11b8\0\u1209\0\u125a\0\u12ab\0\u04bf\0\u12fc\0\u134d\0\u139e"+
    "\0\u13ef\0\u1440\0\u1491\0\u14e2\0\u1533\0\u1584\0\u15d5\0\u1626"+
    "\0\u1677\0\u16c8\0\u1719\0\u176a\0\u17bb\0\u180c\0\u185d\0\u04bf"+
    "\0\u18ae\0\u18ff\0\u1950\0\u19a1\0\u19f2\0\u1a43\0\u1a94\0\u1ae5"+
    "\0\u1b36\0\121\0\u1b87\0\u1bd8\0\u1c29\0\u1c7a\0\u1ccb\0\u0f81"+
    "\0\u1d1c\0\u1d6d\0\u1dbe\0\u1e0f\0\u1e60\0\u1eb1\0\u1f02\0\u1f53"+
    "\0\u1fa4\0\u04bf\0\u1ff5\0\u2046\0\u2097\0\u20e8\0\u2139\0\u218a"+
    "\0\u21db\0\u04bf\0\u222c\0\u227d\0\u22ce\0\u04bf\0\u231f\0\u2370"+
    "\0\u23c1\0\u2412\0\u2463\0\u24b4\0\u2505\0\u2556\0\u25a7\0\u25f8"+
    "\0\u2649\0\u269a\0\u26eb\0\u273c\0\u278d\0\u27de\0\u282f\0\u2880"+
    "\0\u28d1\0\u2922\0\u2973\0\u29c4\0\u2a15\0\u2a66\0\u2ab7\0\u04bf"+
    "\0\u2b08\0\u2b59\0\u2baa\0\u2bfb\0\u04bf\0\u2c4c\0\u2c9d\0\u04bf"+
    "\0\u04bf\0\u2cee\0\u2d3f\0\u2d90\0\u2de1\0\u2e32\0\u2e83\0\u2ed4"+
    "\0\u04bf\0\u2f25\0\u2f76\0\u2fc7\0\u3018\0\u3069\0\u30ba\0\u04bf"+
    "\0\u310b\0\u315c\0\u31ad\0\u31fe\0\u324f\0\u32a0\0\u32f1\0\u3342"+
    "\0\u3393\0\u33e4\0\u3435\0\u3486\0\u34d7\0\u3528\0\u3579\0\u35ca"+
    "\0\u361b\0\u04bf\0\u366c\0\u36bd\0\u370e\0\u375f\0\u04bf\0\u37b0"+
    "\0\u3801\0\u3852\0\u38a3\0\u38f4\0\u3945\0\u3996\0\u04bf\0\u39e7"+
    "\0\u04bf\0\u04bf\0\u3a38\0\u3a89\0\u3ada\0\u3b2b\0\u3b7c\0\u04bf"+
    "\0\u3bcd\0\u3c1e\0\u3c6f\0\u3cc0\0\u3d11\0\u3d62\0\u3db3\0\u3e04"+
    "\0\u04bf\0\u3e55\0\u3ea6\0\u3ef7\0\u3f48\0\u04bf\0\u04bf\0\u3f99"+
    "\0\u3fea\0\u403b\0\u408c\0\u04bf\0\u40dd\0\u412e\0\u417f\0\u41d0"+
    "\0\u04bf\0\u4221\0\u4272\0\u42c3\0\u04bf\0\u04bf\0\u4314\0\u4365"+
    "\0\u04bf\0\u04bf\0\u43b6\0\u04bf\0\u04bf\0\u4407\0\121\0\u4458"+
    "\0\121\0\u44a9\0\121\0\u04bf\0\u44fa\0\u454b\0\u459c\0\u45ed"+
    "\0\u463e\0\u04bf\0\u468f\0\u46e0\0\u04bf\0\u04bf\0\u4731\0\u04bf"+
    "\0\u4782\0\u04bf\0\u47d3\0\u4824\0\u4875\0\u48c6\0\u4917\0\u4968"+
    "\0\u49b9\0\u04bf\0\u04bf\0\u4a0a\0\u4a5b\0\u4aac\0\u4afd\0\u4b4e"+
    "\0\u4b9f\0\u4bf0\0\u4c41\0\u4c92\0\u4ce3\0\u4d34\0\u04bf\0\u4d85"+
    "\0\u4dd6\0\u04bf\0\u4e27\0\u4e78\0\u4ec9\0\u4f1a\0\u4f6b\0\u4fbc"+
    "\0\u500d\0\u04bf\0\u505e\0\u50af\0\u5100\0\u5151\0\u51a2\0\u51f3"+
    "\0\u04bf\0\u5244\0\u04bf\0\u5295\0\u52e6\0\u5337\0\u5388\0\u53d9"+
    "\0\u542a\0\u04bf\0\u547b\0\u54cc\0\u551d\0\u04bf\0\u556e\0\u55bf"+
    "\0\u04bf";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[345];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\2\31\1\42\1\43\1\31\1\44\1\45"+
    "\1\31\1\46\1\47\1\50\1\31\1\51\1\52\1\31"+
    "\1\53\1\31\1\54\1\55\1\56\3\31\1\57\1\60"+
    "\1\61\2\31\1\62\1\63\1\31\1\64\1\31\1\65"+
    "\1\66\1\67\1\31\1\70\2\31\1\71\1\31\1\72"+
    "\1\73\1\74\1\75\122\0\2\3\1\0\1\3\121\0"+
    "\1\76\113\0\2\5\1\0\1\5\1\0\1\5\1\77"+
    "\112\5\23\0\1\100\6\0\6\100\30\0\6\100\23\0"+
    "\2\7\1\101\116\7\12\0\1\102\107\0\2\103\1\0"+
    "\1\103\16\0\1\104\116\0\1\105\114\0\1\106\124\0"+
    "\1\107\1\0\1\22\76\0\2\110\1\0\1\110\16\0"+
    "\1\111\3\0\1\112\120\0\1\113\120\0\1\114\114\0"+
    "\1\31\6\0\32\31\3\0\26\31\27\0\1\31\6\0"+
    "\13\31\1\115\16\31\3\0\26\31\27\0\1\31\6\0"+
    "\24\31\1\116\5\31\3\0\26\31\27\0\1\31\6\0"+
    "\16\31\1\117\2\31\1\120\10\31\3\0\26\31\27\0"+
    "\1\31\6\0\13\31\1\121\16\31\3\0\26\31\27\0"+
    "\1\31\6\0\16\31\1\122\13\31\3\0\26\31\27\0"+
    "\1\31\6\0\21\31\1\123\10\31\3\0\26\31\27\0"+
    "\1\31\6\0\16\31\1\124\13\31\3\0\26\31\27\0"+
    "\1\31\6\0\5\31\1\125\24\31\3\0\26\31\27\0"+
    "\1\31\6\0\10\31\1\126\21\31\3\0\26\31\27\0"+
    "\1\31\6\0\16\31\1\127\5\31\1\130\5\31\3\0"+
    "\26\31\27\0\1\31\6\0\17\31\1\131\12\31\3\0"+
    "\26\31\27\0\1\31\6\0\24\31\1\132\5\31\3\0"+
    "\26\31\27\0\1\31\6\0\4\31\1\133\25\31\3\0"+
    "\26\31\27\0\1\31\6\0\1\134\3\31\1\135\5\31"+
    "\1\136\17\31\3\0\26\31\27\0\1\31\6\0\1\137"+
    "\3\31\1\140\25\31\3\0\26\31\27\0\1\31\6\0"+
    "\4\31\1\141\25\31\3\0\26\31\27\0\1\31\6\0"+
    "\7\31\1\142\22\31\3\0\26\31\27\0\1\31\6\0"+
    "\4\31\1\143\25\31\3\0\26\31\27\0\1\31\6\0"+
    "\32\31\3\0\16\31\1\144\7\31\27\0\1\31\6\0"+
    "\32\31\3\0\20\31\1\145\5\31\27\0\1\31\6\0"+
    "\32\31\3\0\13\31\1\146\12\31\27\0\1\31\6\0"+
    "\32\31\3\0\5\31\1\147\20\31\27\0\1\31\6\0"+
    "\32\31\3\0\15\31\1\150\10\31\27\0\1\31\6\0"+
    "\32\31\3\0\1\31\1\151\24\31\27\0\1\31\6\0"+
    "\32\31\3\0\23\31\1\152\2\31\27\0\1\31\6\0"+
    "\32\31\3\0\17\31\1\153\1\154\5\31\27\0\1\31"+
    "\6\0\32\31\3\0\16\31\1\155\7\31\27\0\1\31"+
    "\6\0\32\31\3\0\17\31\1\156\2\31\1\157\3\31"+
    "\27\0\1\31\6\0\32\31\3\0\10\31\1\160\1\161"+
    "\14\31\122\0\1\162\25\0\1\163\6\0\6\163\30\0"+
    "\6\163\24\0\2\164\1\0\1\164\12\0\1\165\3\0"+
    "\1\104\75\0\15\166\1\167\103\166\23\0\1\170\76\0"+
    "\2\110\1\0\1\110\16\0\1\111\76\0\2\171\1\0"+
    "\1\171\12\0\1\172\3\0\1\111\120\0\1\31\6\0"+
    "\1\173\23\31\1\174\5\31\3\0\26\31\27\0\1\31"+
    "\6\0\21\31\1\175\10\31\3\0\26\31\27\0\1\31"+
    "\6\0\23\31\1\176\1\177\5\31\3\0\26\31\27\0"+
    "\1\31\6\0\16\31\1\200\13\31\3\0\26\31\27\0"+
    "\1\31\6\0\22\31\1\201\7\31\3\0\26\31\27\0"+
    "\1\31\6\0\21\31\1\202\10\31\3\0\26\31\27\0"+
    "\1\31\6\0\4\31\1\203\25\31\3\0\26\31\27\0"+
    "\1\31\6\0\21\31\1\204\10\31\3\0\26\31\27\0"+
    "\1\31\6\0\15\31\1\205\14\31\3\0\26\31\27\0"+
    "\1\31\6\0\15\31\1\206\14\31\3\0\26\31\27\0"+
    "\1\31\6\0\13\31\1\207\16\31\3\0\26\31\27\0"+
    "\1\31\6\0\4\31\1\210\25\31\3\0\26\31\27\0"+
    "\1\31\6\0\21\31\1\211\10\31\3\0\26\31\27\0"+
    "\1\31\6\0\3\31\1\212\26\31\3\0\26\31\27\0"+
    "\1\31\6\0\15\31\1\213\14\31\3\0\26\31\27\0"+
    "\1\31\6\0\2\31\1\214\10\31\1\215\16\31\3\0"+
    "\26\31\27\0\1\31\6\0\30\31\1\216\1\31\3\0"+
    "\26\31\27\0\1\31\6\0\1\31\1\217\30\31\3\0"+
    "\26\31\27\0\1\31\6\0\27\31\1\220\2\31\3\0"+
    "\26\31\27\0\1\31\6\0\21\31\1\221\10\31\3\0"+
    "\26\31\27\0\1\31\6\0\10\31\1\222\21\31\3\0"+
    "\26\31\27\0\1\31\6\0\13\31\1\223\16\31\3\0"+
    "\26\31\27\0\1\31\6\0\32\31\3\0\15\31\1\224"+
    "\2\31\1\225\5\31\27\0\1\31\6\0\32\31\3\0"+
    "\1\31\1\226\24\31\27\0\1\31\6\0\32\31\3\0"+
    "\5\31\1\227\20\31\27\0\1\31\6\0\32\31\3\0"+
    "\11\31\1\230\14\31\27\0\1\31\6\0\32\31\3\0"+
    "\2\31\1\231\23\31\27\0\1\31\6\0\32\31\3\0"+
    "\14\31\1\232\11\31\27\0\1\31\6\0\32\31\3\0"+
    "\22\31\1\233\3\31\27\0\1\31\6\0\32\31\3\0"+
    "\11\31\1\234\14\31\27\0\1\31\6\0\32\31\3\0"+
    "\11\31\1\235\14\31\27\0\1\31\6\0\32\31\3\0"+
    "\5\31\1\236\20\31\27\0\1\31\6\0\32\31\3\0"+
    "\20\31\1\237\4\31\1\240\27\0\1\31\6\0\32\31"+
    "\3\0\16\31\1\241\7\31\27\0\1\31\6\0\32\31"+
    "\3\0\4\31\1\242\21\31\27\0\1\243\6\0\6\243"+
    "\30\0\6\243\24\0\2\164\1\0\1\164\12\0\1\165"+
    "\102\0\2\165\1\0\1\165\16\0\1\244\75\0\15\166"+
    "\1\245\103\166\15\0\1\167\4\0\1\101\77\0\2\171"+
    "\1\0\1\171\12\0\1\172\102\0\2\172\1\0\1\172"+
    "\16\0\1\246\120\0\1\31\6\0\2\31\1\247\27\31"+
    "\3\0\26\31\27\0\1\31\6\0\4\31\1\250\25\31"+
    "\3\0\26\31\27\0\1\31\6\0\22\31\1\251\7\31"+
    "\3\0\26\31\27\0\1\31\6\0\23\31\1\252\6\31"+
    "\3\0\26\31\27\0\1\31\6\0\1\31\1\253\30\31"+
    "\3\0\26\31\27\0\1\31\6\0\17\31\1\254\12\31"+
    "\3\0\26\31\27\0\1\31\6\0\4\31\1\255\25\31"+
    "\3\0\26\31\27\0\1\31\6\0\4\31\1\256\25\31"+
    "\3\0\26\31\27\0\1\31\6\0\10\31\1\257\21\31"+
    "\3\0\26\31\27\0\1\31\6\0\4\31\1\260\25\31"+
    "\3\0\26\31\27\0\1\31\6\0\16\31\1\261\13\31"+
    "\3\0\26\31\27\0\1\31\6\0\23\31\1\262\6\31"+
    "\3\0\26\31\27\0\1\31\6\0\15\31\1\263\14\31"+
    "\3\0\26\31\27\0\1\31\6\0\17\31\1\264\12\31"+
    "\3\0\26\31\27\0\1\31\6\0\22\31\1\265\7\31"+
    "\3\0\26\31\27\0\1\31\6\0\23\31\1\266\6\31"+
    "\3\0\26\31\27\0\1\31\6\0\4\31\1\267\25\31"+
    "\3\0\26\31\27\0\1\31\6\0\13\31\1\270\16\31"+
    "\3\0\26\31\27\0\1\31\6\0\23\31\1\271\6\31"+
    "\3\0\26\31\27\0\1\31\6\0\23\31\1\272\6\31"+
    "\3\0\26\31\27\0\1\31\6\0\13\31\1\273\7\31"+
    "\1\274\6\31\3\0\26\31\27\0\1\31\6\0\13\31"+
    "\1\275\16\31\3\0\26\31\27\0\1\31\6\0\32\31"+
    "\3\0\22\31\1\276\3\31\27\0\1\31\6\0\32\31"+
    "\3\0\20\31\1\277\5\31\27\0\1\31\6\0\32\31"+
    "\3\0\24\31\1\300\1\31\27\0\1\31\6\0\32\31"+
    "\3\0\14\31\1\301\11\31\27\0\1\31\6\0\32\31"+
    "\3\0\7\31\1\302\16\31\27\0\1\31\6\0\32\31"+
    "\3\0\5\31\1\303\20\31\27\0\1\31\6\0\32\31"+
    "\3\0\2\31\1\304\23\31\27\0\1\31\6\0\32\31"+
    "\3\0\11\31\1\305\14\31\27\0\1\31\6\0\32\31"+
    "\3\0\5\31\1\306\20\31\27\0\1\31\6\0\32\31"+
    "\3\0\15\31\1\307\10\31\27\0\1\31\6\0\32\31"+
    "\3\0\3\31\1\310\22\31\27\0\1\31\6\0\32\31"+
    "\3\0\11\31\1\311\14\31\27\0\1\31\6\0\32\31"+
    "\3\0\13\31\1\312\12\31\27\0\1\31\6\0\32\31"+
    "\3\0\1\313\25\31\27\0\1\31\6\0\32\31\3\0"+
    "\22\31\1\314\3\31\27\0\1\315\6\0\6\315\30\0"+
    "\6\315\24\0\2\316\1\0\1\316\12\0\1\317\3\0"+
    "\1\244\75\0\15\166\1\245\4\166\1\101\76\166\1\0"+
    "\2\320\1\0\1\320\12\0\1\321\3\0\1\246\120\0"+
    "\1\31\6\0\12\31\1\322\17\31\3\0\26\31\27\0"+
    "\1\31\6\0\10\31\1\323\21\31\3\0\26\31\27\0"+
    "\1\31\6\0\4\31\1\324\25\31\3\0\26\31\27\0"+
    "\1\31\6\0\13\31\1\325\16\31\3\0\26\31\27\0"+
    "\1\31\6\0\32\31\3\0\1\326\25\31\27\0\1\31"+
    "\6\0\15\31\1\327\14\31\3\0\26\31\27\0\1\31"+
    "\6\0\31\31\1\330\3\0\26\31\27\0\1\31\6\0"+
    "\10\31\1\331\21\31\3\0\26\31\27\0\1\31\6\0"+
    "\32\31\3\0\1\332\25\31\27\0\1\31\6\0\13\31"+
    "\1\333\16\31\3\0\26\31\27\0\1\31\6\0\32\31"+
    "\3\0\1\334\25\31\27\0\1\31\6\0\10\31\1\335"+
    "\21\31\3\0\26\31\27\0\1\31\6\0\2\31\1\336"+
    "\27\31\3\0\26\31\27\0\1\31\6\0\4\31\1\337"+
    "\25\31\3\0\26\31\27\0\1\31\6\0\10\31\1\340"+
    "\21\31\3\0\26\31\27\0\1\31\6\0\4\31\1\341"+
    "\25\31\3\0\26\31\27\0\1\31\6\0\4\31\1\342"+
    "\25\31\3\0\26\31\27\0\1\31\6\0\16\31\1\343"+
    "\13\31\3\0\26\31\27\0\1\31\6\0\32\31\3\0"+
    "\5\31\1\344\20\31\27\0\1\31\6\0\32\31\3\0"+
    "\5\31\1\345\20\31\27\0\1\31\6\0\32\31\3\0"+
    "\5\31\1\346\20\31\27\0\1\31\6\0\32\31\3\0"+
    "\10\31\1\347\15\31\27\0\1\31\6\0\32\31\3\0"+
    "\13\31\1\350\12\31\27\0\1\31\6\0\32\31\3\0"+
    "\5\31\1\351\20\31\27\0\1\31\6\0\32\31\3\0"+
    "\16\31\1\352\7\31\27\0\1\31\6\0\32\31\3\0"+
    "\15\31\1\353\10\31\27\0\1\31\6\0\32\31\3\0"+
    "\22\31\1\354\3\31\27\0\1\31\6\0\32\31\3\0"+
    "\11\31\1\355\14\31\27\0\1\31\6\0\32\31\3\0"+
    "\15\31\1\356\10\31\27\0\1\31\6\0\32\31\3\0"+
    "\5\31\1\357\20\31\27\0\1\31\6\0\32\31\3\0"+
    "\11\31\1\360\14\31\27\0\1\31\6\0\32\31\3\0"+
    "\10\31\1\361\15\31\27\0\1\362\6\0\6\362\30\0"+
    "\6\362\24\0\2\316\1\0\1\316\12\0\1\317\102\0"+
    "\2\317\1\0\1\317\16\0\1\363\76\0\2\320\1\0"+
    "\1\320\12\0\1\321\102\0\2\321\1\0\1\321\16\0"+
    "\1\364\120\0\1\31\6\0\25\31\1\365\4\31\3\0"+
    "\26\31\27\0\1\31\6\0\3\31\1\366\26\31\3\0"+
    "\26\31\27\0\1\31\6\0\4\31\1\367\25\31\3\0"+
    "\26\31\27\0\1\31\6\0\20\31\1\370\11\31\3\0"+
    "\26\31\27\0\1\31\6\0\16\31\1\371\13\31\3\0"+
    "\26\31\27\0\1\31\6\0\17\31\1\372\12\31\3\0"+
    "\26\31\27\0\1\31\6\0\20\31\1\373\11\31\3\0"+
    "\26\31\27\0\1\31\6\0\4\31\1\374\25\31\3\0"+
    "\26\31\27\0\1\31\6\0\22\31\1\375\7\31\3\0"+
    "\26\31\27\0\1\31\6\0\16\31\1\376\13\31\3\0"+
    "\26\31\27\0\1\31\6\0\23\31\1\377\6\31\3\0"+
    "\26\31\27\0\1\31\6\0\2\31\1\u0100\27\31\3\0"+
    "\26\31\27\0\1\31\6\0\26\31\1\u0101\3\31\3\0"+
    "\26\31\27\0\1\31\6\0\32\31\3\0\15\31\1\u0102"+
    "\10\31\27\0\1\31\6\0\32\31\3\0\3\31\1\u0103"+
    "\22\31\27\0\1\31\6\0\32\31\3\0\15\31\1\u0104"+
    "\10\31\27\0\1\31\6\0\32\31\3\0\22\31\1\u0105"+
    "\3\31\27\0\1\31\6\0\32\31\3\0\20\31\1\u0106"+
    "\5\31\27\0\1\31\6\0\32\31\3\0\15\31\1\u0107"+
    "\10\31\27\0\1\31\6\0\32\31\3\0\22\31\1\u0108"+
    "\3\31\27\0\1\31\6\0\27\31\1\u0109\1\u010a\1\31"+
    "\3\0\26\31\27\0\1\31\6\0\32\31\3\0\1\31"+
    "\1\u010b\24\31\27\0\1\31\6\0\32\31\3\0\7\31"+
    "\1\u010c\16\31\27\0\1\31\6\0\32\31\3\0\21\31"+
    "\1\u010d\4\31\27\0\1\31\6\0\32\31\3\0\21\31"+
    "\1\u010e\4\31\27\0\1\u010f\6\0\6\u010f\30\0\6\u010f"+
    "\24\0\2\u0110\1\0\1\u0110\7\0\1\u0111\6\0\1\363"+
    "\76\0\2\u0112\1\0\1\u0112\16\0\1\364\4\0\1\u0113"+
    "\113\0\1\31\6\0\4\31\1\u0114\25\31\3\0\26\31"+
    "\27\0\1\31\6\0\24\31\1\u0115\5\31\3\0\26\31"+
    "\27\0\1\31\6\0\15\31\1\u0116\14\31\3\0\26\31"+
    "\27\0\1\31\6\0\13\31\1\u0117\16\31\3\0\26\31"+
    "\27\0\1\31\6\0\24\31\1\u0118\5\31\3\0\26\31"+
    "\27\0\1\31\6\0\4\31\1\u0119\25\31\3\0\26\31"+
    "\27\0\1\31\6\0\15\31\1\u011a\14\31\3\0\26\31"+
    "\27\0\1\31\6\0\32\31\3\0\1\u011b\25\31\27\0"+
    "\1\31\6\0\1\u011c\31\31\3\0\26\31\27\0\1\31"+
    "\6\0\32\31\3\0\22\31\1\u011d\3\31\27\0\1\31"+
    "\6\0\32\31\3\0\22\31\1\u011e\3\31\27\0\1\31"+
    "\6\0\32\31\3\0\22\31\1\u011f\3\31\27\0\1\31"+
    "\6\0\32\31\3\0\21\31\1\u0120\4\31\27\0\1\31"+
    "\6\0\32\31\3\0\1\31\1\u0121\24\31\27\0\1\31"+
    "\6\0\32\31\3\0\13\31\1\u0122\12\31\27\0\1\31"+
    "\6\0\32\31\3\0\1\u0123\25\31\5\0\2\u0110\1\0"+
    "\1\u0110\7\0\1\u0111\105\0\2\u0112\1\0\1\u0112\23\0"+
    "\1\u0113\113\0\1\31\6\0\4\31\1\u0124\25\31\3\0"+
    "\26\31\27\0\1\31\6\0\23\31\1\u0125\6\31\3\0"+
    "\26\31\27\0\1\31\6\0\4\31\1\u0126\25\31\3\0"+
    "\26\31\27\0\1\31\6\0\4\31\1\u0127\25\31\3\0"+
    "\26\31\27\0\1\31\6\0\21\31\1\u0128\10\31\3\0"+
    "\26\31\27\0\1\31\6\0\20\31\1\u0129\11\31\3\0"+
    "\26\31\27\0\1\31\6\0\13\31\1\u012a\16\31\3\0"+
    "\26\31\27\0\1\31\6\0\32\31\3\0\21\31\1\u012b"+
    "\4\31\27\0\1\31\6\0\32\31\3\0\22\31\1\u012c"+
    "\3\31\27\0\1\31\6\0\32\31\3\0\22\31\1\u012d"+
    "\3\31\27\0\1\31\6\0\22\31\1\u012e\7\31\3\0"+
    "\26\31\27\0\1\31\6\0\1\u012f\31\31\3\0\26\31"+
    "\27\0\1\31\6\0\32\31\3\0\1\u0130\25\31\27\0"+
    "\1\31\6\0\22\31\1\u0131\7\31\3\0\26\31\27\0"+
    "\1\31\6\0\10\31\1\u0132\21\31\3\0\26\31\27\0"+
    "\1\31\6\0\24\31\1\u0133\5\31\3\0\26\31\27\0"+
    "\1\31\6\0\32\31\3\0\11\31\1\u0134\14\31\27\0"+
    "\1\31\6\0\32\31\3\0\10\31\1\u0135\15\31\27\0"+
    "\1\31\6\0\23\31\1\u0136\6\31\3\0\26\31\27\0"+
    "\1\31\6\0\13\31\1\u0137\16\31\3\0\26\31\27\0"+
    "\1\31\6\0\20\31\1\u0138\11\31\3\0\26\31\27\0"+
    "\1\31\6\0\23\31\1\u0139\6\31\3\0\26\31\27\0"+
    "\1\31\6\0\5\31\1\u013a\24\31\3\0\26\31\27\0"+
    "\1\31\6\0\4\31\1\u013b\25\31\3\0\26\31\27\0"+
    "\1\31\6\0\32\31\3\0\16\31\1\u013c\7\31\27\0"+
    "\1\31\6\0\32\31\3\0\1\31\1\u013d\24\31\27\0"+
    "\1\31\6\0\10\31\1\u013e\21\31\3\0\26\31\27\0"+
    "\1\31\6\0\24\31\1\u013f\5\31\3\0\26\31\27\0"+
    "\1\31\6\0\10\31\1\u0140\21\31\3\0\26\31\27\0"+
    "\1\31\6\0\22\31\1\u0141\7\31\3\0\26\31\27\0"+
    "\1\31\6\0\32\31\3\0\15\31\1\u0142\10\31\27\0"+
    "\1\31\6\0\32\31\3\0\22\31\1\u0143\3\31\27\0"+
    "\1\31\6\0\16\31\1\u0144\13\31\3\0\26\31\27\0"+
    "\1\31\6\0\4\31\1\u0145\25\31\3\0\26\31\27\0"+
    "\1\31\6\0\16\31\1\u0146\13\31\3\0\26\31\27\0"+
    "\1\31\6\0\23\31\1\u0147\6\31\3\0\26\31\27\0"+
    "\1\31\6\0\32\31\3\0\1\u0148\25\31\27\0\1\31"+
    "\6\0\15\31\1\u0149\14\31\3\0\26\31\27\0\1\31"+
    "\6\0\22\31\1\u014a\7\31\3\0\26\31\27\0\1\31"+
    "\6\0\15\31\1\u014b\14\31\3\0\26\31\27\0\1\31"+
    "\6\0\10\31\1\u014c\21\31\3\0\26\31\27\0\1\31"+
    "\6\0\32\31\3\0\17\31\1\u014d\6\31\27\0\1\31"+
    "\6\0\23\31\1\u014e\6\31\3\0\26\31\27\0\1\31"+
    "\6\0\16\31\1\u014f\13\31\3\0\26\31\27\0\1\31"+
    "\6\0\32\31\3\0\16\31\1\u0150\7\31\27\0\1\31"+
    "\6\0\10\31\1\u0151\21\31\3\0\26\31\27\0\1\31"+
    "\6\0\15\31\1\u0152\14\31\3\0\26\31\27\0\1\31"+
    "\6\0\32\31\3\0\12\31\1\u0153\13\31\27\0\1\31"+
    "\6\0\16\31\1\u0154\13\31\3\0\26\31\27\0\1\31"+
    "\6\0\32\31\3\0\5\31\1\u0155\20\31\27\0\1\31"+
    "\6\0\15\31\1\u0156\14\31\3\0\26\31\27\0\1\31"+
    "\6\0\32\31\3\0\14\31\1\u0157\11\31\27\0\1\31"+
    "\6\0\32\31\3\0\16\31\1\u0158\7\31\27\0\1\31"+
    "\6\0\32\31\3\0\15\31\1\u0159\10\31\4\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[22032];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\1\11\2\1\5\11\3\1\2\11"+
    "\3\1\1\11\23\1\3\11\13\1\1\11\1\1\4\11"+
    "\1\0\2\11\2\0\1\11\4\0\3\11\45\1\1\11"+
    "\5\0\1\1\2\0\50\1\4\0\46\1\5\0\40\1"+
    "\3\0\32\1\1\11\1\0\1\11\1\0\1\11\106\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[345];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    public static class ErrorLexico
    {
        public String lexema;
        public int linea;
        public int columna;
        public String descripcion;
        public ErrorLexico(String lexema, int linea, int columna, String descripcion)
        {
            this.lexema = lexema;
            this.linea = linea;
            this.columna = columna;
            this.descripcion = descripcion;
        }
    }
    public ArrayList<ErrorLexico> listaErrores = new ArrayList<>();
    private Symbol symbol(int type, Object value)
    {
        return new Symbol(type, yyline + 1, yycolumn + 1, value);
    }

    private void reportarError(String lexema, String descripcion)
    {
        listaErrores.add(new ErrorLexico(lexema, yyline + 1, yycolumn + 1, descripcion));
        System.err.println("Error Léxico en línea " + (yyline + 1) + ", columna " + (yycolumn + 1) + ": " + descripcion + " '" + lexema + "'");
    }

    public java.util.ArrayList<ErrorCompi> erroresLexicos = new java.util.ArrayList<>();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerFormulario(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { String lexema = yytext();
    int linea = yyline + 1;
    int columna = yycolumn + 1;
    erroresLexicos.add(new ErrorCompi("Léxico", "Caracter no válido: " + lexema, linea, columna));
    System.err.println("Error Léxico en (" + linea + ", " + columna + "): Caracter no válido: " + lexema);
            }
          // fall through
          case 84: break;
          case 2:
            { /* Ignorar */
            }
          // fall through
          case 85: break;
          case 3:
            { return symbol(sym.NOT, yytext());
            }
          // fall through
          case 86: break;
          case 4:
            { String lexema = yytext();
    int linea = yyline + 1;
    int columna = yycolumn + 1;
    erroresLexicos.add(new ErrorCompi("Léxico", "Cadena sin cerrar: " + lexema, linea, columna));
    System.err.println("Error Léxico en (" + linea + ", " + columna + "): Cadena sin cerrar");
    return symbol(sym.CADENA, lexema + "\"");
            }
          // fall through
          case 87: break;
          case 5:
            { return symbol(sym.MODULO, yytext());
            }
          // fall through
          case 88: break;
          case 6:
            { return symbol(sym.PAR_IZQ, yytext());
            }
          // fall through
          case 89: break;
          case 7:
            { return symbol(sym.PAR_DER, yytext());
            }
          // fall through
          case 90: break;
          case 8:
            { return symbol(sym.POR, yytext());
            }
          // fall through
          case 91: break;
          case 9:
            { return symbol(sym.MAS, yytext());
            }
          // fall through
          case 92: break;
          case 10:
            { return symbol(sym.COMA, yytext());
            }
          // fall through
          case 93: break;
          case 11:
            { return symbol(sym.MENOS, yytext());
            }
          // fall through
          case 94: break;
          case 12:
            { return symbol(sym.PUNTO, yytext());
            }
          // fall through
          case 95: break;
          case 13:
            { return symbol(sym.DIV, yytext());
            }
          // fall through
          case 96: break;
          case 14:
            { return symbol(sym.ENTERO, Double.parseDouble(yytext()));
            }
          // fall through
          case 97: break;
          case 15:
            { return symbol(sym.DOS_PUNTOS, yytext());
            }
          // fall through
          case 98: break;
          case 16:
            { return symbol(sym.PUNTO_Y_COMA, yytext());
            }
          // fall through
          case 99: break;
          case 17:
            { return symbol(sym.MENOR, yytext());
            }
          // fall through
          case 100: break;
          case 18:
            { return symbol(sym.IGUAL_ASIG, yytext());
            }
          // fall through
          case 101: break;
          case 19:
            { return symbol(sym.MAYOR, yytext());
            }
          // fall through
          case 102: break;
          case 20:
            { return symbol(sym.COMODIN, yytext());
            }
          // fall through
          case 103: break;
          case 21:
            { return symbol(sym.ID, yytext());
            }
          // fall through
          case 104: break;
          case 22:
            { return symbol(sym.CORCHETE_IZQ, yytext());
            }
          // fall through
          case 105: break;
          case 23:
            { return symbol(sym.CORCHETE_DER, yytext());
            }
          // fall through
          case 106: break;
          case 24:
            { return symbol(sym.POTENCIA, yytext());
            }
          // fall through
          case 107: break;
          case 25:
            { return symbol(sym.LLAVE_IZQ, yytext());
            }
          // fall through
          case 108: break;
          case 26:
            { return symbol(sym.LLAVE_DER, yytext());
            }
          // fall through
          case 109: break;
          case 27:
            { return symbol(sym.DIFERENTE, yytext());
            }
          // fall through
          case 110: break;
          case 28:
            { return symbol(sym.CADENA, yytext());
            }
          // fall through
          case 111: break;
          case 29:
            { return symbol(sym.AND, yytext());
            }
          // fall through
          case 112: break;
          case 30:
            { return symbol(sym.PUNTO_PUNTO, yytext());
            }
          // fall through
          case 113: break;
          case 31:
            { return symbol(sym.MENOR_IGUAL, yytext());
            }
          // fall through
          case 114: break;
          case 32:
            { return symbol(sym.IGUALDAD, yytext());
            }
          // fall through
          case 115: break;
          case 33:
            { return symbol(sym.MAYOR_IGUAL, yytext());
            }
          // fall through
          case 116: break;
          case 34:
            { return symbol(sym.DO, yytext());
            }
          // fall through
          case 117: break;
          case 35:
            { return symbol(sym.IF, yytext());
            }
          // fall through
          case 118: break;
          case 36:
            { return symbol(sym.IN, yytext());
            }
          // fall through
          case 119: break;
          case 37:
            { return symbol(sym.OR, yytext());
            }
          // fall through
          case 120: break;
          case 38:
            { return symbol(sym.DECIMAL, Double.parseDouble(yytext()));
            }
          // fall through
          case 121: break;
          case 39:
            { return symbol(sym.FOR, yytext());
            }
          // fall through
          case 122: break;
          case 40:
            { return symbol(sym.COLOR_RED, yytext());
            }
          // fall through
          case 123: break;
          case 41:
            { return symbol(sym.COLOR_SKY, yytext());
            }
          // fall through
          case 124: break;
          case 42:
            { return symbol(sym.COLOR_BLUE, yytext());
            }
          // fall through
          case 125: break;
          case 43:
            { return symbol(sym.ELSE, yytext());
            }
          // fall through
          case 126: break;
          case 44:
            { return symbol(sym.ENUM_LINE, yytext());
            }
          // fall through
          case 127: break;
          case 45:
            { return symbol(sym.ENUM_MONO, yytext());
            }
          // fall through
          case 128: break;
          case 46:
            { return symbol(sym.TEXT, yytext());
            }
          // fall through
          case 129: break;
          case 47:
            { return symbol(sym.FUNC_DRAW, yytext());
            }
          // fall through
          case 130: break;
          case 48:
            { return symbol(sym.COLOR_BLACK, yytext());
            }
          // fall through
          case 131: break;
          case 49:
            { return symbol(sym.COLOR_GREEN, yytext());
            }
          // fall through
          case 132: break;
          case 50:
            { return symbol(sym.TABLE, yytext());
            }
          // fall through
          case 133: break;
          case 51:
            { return symbol(sym.WHILE, yytext());
            }
          // fall through
          case 134: break;
          case 52:
            { return symbol(sym.COLOR_WHITE, yytext());
            }
          // fall through
          case 135: break;
          case 53:
            { return symbol(sym.ATTR_LABEL, yytext());
            }
          // fall through
          case 136: break;
          case 54:
            { return symbol(sym.ATTR_WIDTH, yytext());
            }
          // fall through
          case 137: break;
          case 55:
            { return symbol(sym.ENUM_DOTTED, yytext());
            }
          // fall through
          case 138: break;
          case 56:
            { return symbol(sym.ENUM_DOUBLE, yytext());
            }
          // fall through
          case 139: break;
          case 57:
            { return symbol(sym.COLOR_PURPLE, yytext());
            }
          // fall through
          case 140: break;
          case 58:
            { return symbol(sym.COLOR_YELLOW, yytext());
            }
          // fall through
          case 141: break;
          case 59:
            { return symbol(sym.ATTR_HEIGHT, yytext());
            }
          // fall through
          case 142: break;
          case 60:
            { return symbol(sym.TYPE_NUMBER, yytext());
            }
          // fall through
          case 143: break;
          case 61:
            { return symbol(sym.ATTR_POINTX, yytext());
            }
          // fall through
          case 144: break;
          case 62:
            { return symbol(sym.ATTR_POINTY, yytext());
            }
          // fall through
          case 145: break;
          case 63:
            { return symbol(sym.TYPE_STRING, yytext());
            }
          // fall through
          case 146: break;
          case 64:
            { return symbol(sym.ATTR_STYLES, yytext());
            }
          // fall through
          case 147: break;
          case 65:
            { return symbol(sym.VAL_COLOR_HEX, yytext());
            }
          // fall through
          case 148: break;
          case 66:
            { return symbol(sym.VAL_COLOR_RGB, yytext());
            }
          // fall through
          case 149: break;
          case 67:
            { return symbol(sym.VAL_COLOR_HSL, yytext());
            }
          // fall through
          case 150: break;
          case 68:
            { return symbol(sym.ENUM_CURSIVE, yytext());
            }
          // fall through
          case 151: break;
          case 69:
            { return symbol(sym.SECTION, yytext());
            }
          // fall through
          case 152: break;
          case 70:
            { return symbol(sym.ATTR_CONTENT, yytext());
            }
          // fall through
          case 153: break;
          case 71:
            { return symbol(sym.ATTR_CORRECT, yytext());
            }
          // fall through
          case 154: break;
          case 72:
            { return symbol(sym.ATTR_OPTIONS, yytext());
            }
          // fall through
          case 155: break;
          case 73:
            { return symbol(sym.TYPE_SPECIAL, yytext());
            }
          // fall through
          case 156: break;
          case 74:
            { return symbol(sym.ENUM_VERTICAL, yytext());
            }
          // fall through
          case 157: break;
          case 75:
            { return symbol(sym.ATTR_ELEMENTS, yytext());
            }
          // fall through
          case 158: break;
          case 76:
            { return symbol(sym.ENUM_HORIZONTAL, yytext());
            }
          // fall through
          case 159: break;
          case 77:
            { return symbol(sym.ENUM_SANS_SERIF, yytext());
            }
          // fall through
          case 160: break;
          case 78:
            { return symbol(sym.ATTR_ORIENTATION, yytext());
            }
          // fall through
          case 161: break;
          case 79:
            { return symbol(sym.DROP_QUESTION, yytext());
            }
          // fall through
          case 162: break;
          case 80:
            { return symbol(sym.OPEN_QUESTION, yytext());
            }
          // fall through
          case 163: break;
          case 81:
            { return symbol(sym.SELECT_QUESTION, yytext());
            }
          // fall through
          case 164: break;
          case 82:
            { return symbol(sym.MULTIPLE_QUESTION, yytext());
            }
          // fall through
          case 165: break;
          case 83:
            { return symbol(sym.FUNC_POKEMON, yytext());
            }
          // fall through
          case 166: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
