
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SELECT_QUESTION = 10;
  public static final int ENUM_DOTTED = 34;
  public static final int MENOR_IGUAL = 60;
  public static final int COLOR_WHITE = 43;
  public static final int CORCHETE_DER = 68;
  public static final int ENUM_CURSIVE = 32;
  public static final int TABLE = 6;
  public static final int COLOR_BLACK = 42;
  public static final int LLAVE_IZQ = 69;
  public static final int POTENCIA = 53;
  public static final int MAYOR = 57;
  public static final int ENUM_MONO = 30;
  public static final int COLOR_PURPLE = 39;
  public static final int DROP_QUESTION = 9;
  public static final int ATTR_STYLES = 23;
  public static final int DIFERENTE = 56;
  public static final int PAR_DER = 66;
  public static final int OPEN_QUESTION = 8;
  public static final int POR = 51;
  public static final int ATTR_ELEMENTS = 22;
  public static final int VAL_COLOR_HSL = 46;
  public static final int NOT = 63;
  public static final int FUNC_DRAW = 47;
  public static final int TEXT = 7;
  public static final int DOS_PUNTOS = 72;
  public static final int ENUM_LINE = 33;
  public static final int IGUALDAD = 55;
  public static final int FUNC_POKEMON = 48;
  public static final int TYPE_SPECIAL = 4;
  public static final int COMA = 71;
  public static final int ENTERO = 80;
  public static final int MODULO = 54;
  public static final int ATTR_ORIENTATION = 21;
  public static final int TYPE_NUMBER = 2;
  public static final int ENUM_HORIZONTAL = 29;
  public static final int VAL_COLOR_HEX = 44;
  public static final int ENUM_DOUBLE = 35;
  public static final int WHILE = 14;
  public static final int CORCHETE_IZQ = 67;
  public static final int DECIMAL = 79;
  public static final int ATTR_HEIGHT = 18;
  public static final int ATTR_CORRECT = 27;
  public static final int ATTR_WIDTH = 17;
  public static final int DO = 15;
  public static final int ATTR_CONTENT = 24;
  public static final int FOR = 16;
  public static final int DIV = 52;
  public static final int COMODIN = 73;
  public static final int ELSE = 13;
  public static final int MENOS = 50;
  public static final int MULTIPLE_QUESTION = 11;
  public static final int MENOR = 58;
  public static final int MAS = 49;
  public static final int ENUM_SANS_SERIF = 31;
  public static final int PUNTO_Y_COMA = 74;
  public static final int PAR_IZQ = 65;
  public static final int EOF = 0;
  public static final int LLAVE_DER = 70;
  public static final int ENUM_VERTICAL = 28;
  public static final int ATTR_POINTY = 20;
  public static final int ATTR_POINTX = 19;
  public static final int PUNTO_PUNTO = 76;
  public static final int IN = 75;
  public static final int OR = 62;
  public static final int error = 1;
  public static final int IF = 12;
  public static final int IGUAL_ASIG = 64;
  public static final int ID = 78;
  public static final int COLOR_SKY = 40;
  public static final int ATTR_OPTIONS = 26;
  public static final int COLOR_GREEN = 38;
  public static final int ATTR_LABEL = 25;
  public static final int CADENA = 77;
  public static final int COLOR_RED = 36;
  public static final int TYPE_STRING = 3;
  public static final int AND = 61;
  public static final int COLOR_BLUE = 37;
  public static final int VAL_COLOR_RGB = 45;
  public static final int COLOR_YELLOW = 41;
  public static final int MAYOR_IGUAL = 59;
  public static final int SECTION = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TYPE_NUMBER",
  "TYPE_STRING",
  "TYPE_SPECIAL",
  "SECTION",
  "TABLE",
  "TEXT",
  "OPEN_QUESTION",
  "DROP_QUESTION",
  "SELECT_QUESTION",
  "MULTIPLE_QUESTION",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "ATTR_WIDTH",
  "ATTR_HEIGHT",
  "ATTR_POINTX",
  "ATTR_POINTY",
  "ATTR_ORIENTATION",
  "ATTR_ELEMENTS",
  "ATTR_STYLES",
  "ATTR_CONTENT",
  "ATTR_LABEL",
  "ATTR_OPTIONS",
  "ATTR_CORRECT",
  "ENUM_VERTICAL",
  "ENUM_HORIZONTAL",
  "ENUM_MONO",
  "ENUM_SANS_SERIF",
  "ENUM_CURSIVE",
  "ENUM_LINE",
  "ENUM_DOTTED",
  "ENUM_DOUBLE",
  "COLOR_RED",
  "COLOR_BLUE",
  "COLOR_GREEN",
  "COLOR_PURPLE",
  "COLOR_SKY",
  "COLOR_YELLOW",
  "COLOR_BLACK",
  "COLOR_WHITE",
  "VAL_COLOR_HEX",
  "VAL_COLOR_RGB",
  "VAL_COLOR_HSL",
  "FUNC_DRAW",
  "FUNC_POKEMON",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "POTENCIA",
  "MODULO",
  "IGUALDAD",
  "DIFERENTE",
  "MAYOR",
  "MENOR",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "AND",
  "OR",
  "NOT",
  "IGUAL_ASIG",
  "PAR_IZQ",
  "PAR_DER",
  "CORCHETE_IZQ",
  "CORCHETE_DER",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "COMA",
  "DOS_PUNTOS",
  "COMODIN",
  "PUNTO_Y_COMA",
  "IN",
  "PUNTO_PUNTO",
  "CADENA",
  "ID",
  "DECIMAL",
  "ENTERO"
  };
}

